app_orders:
    resource: "@AppBundle/Controller/OrdersController.php"
    type:     annotation

app_category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

app_manufacturer:
    resource: "@AppBundle/Controller/ManufacturerController.php"
    type:     annotation

app_products:
    resource: "@AppBundle/Controller/ProductsController.php"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"
login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}
#wiki:
#    resource: "@AppBundle/Controller/WikiController.php"
#    type: annotation
employees:
    resource: "@AppBundle/Controller"
    type: annotation

